sudo: false

language: python

# Limit git depth to speed up build
git:
  depth: 5

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-unittests
    - python: 3.5
      env: TOXENV=py35-unittests
    - python: 3.6
      env: TOXENV=py36-unittests
    - python: 3.7-dev
      env: TOXENV=py37-unittests
    - python: 3.6
      env: TOXENV=lint
  allow_failures:
    - python: 3.7-dev

# addons:
#   apt:
#     packages:
#       - aspell
#       - aspell-en

install:
  - pip install tox
  - pip install codecov

script:
  - tox

after_success:
  - codecov

deploy:
  - provider: pypi
    user: facelessuser
    server: https://upload.pypi.org/legacy/
    password:
      secure: ''
    distributions: "sdist bdist_wheel"
    skip_upload_docs: true
    on:
      tags: true
      repo: facelessuser/bracex
      condition: "$TOXENV = lint"
  # - provider: pages
  #   github_token: $GITHUB_TOKEN
  #   name: $GITHUB_USER
  #   email: $GITHUB_EMAIL
  #   skip_cleanup: true
  #   local_dir: site
  #   on:
  #     tags: true
  #     repo: facelessuser/bracex
  #     condition: "$TOXENV = documents"
