build: false

clone_depth: 5

environment:
  matrix:
    - PYTHON: "C:/Python35"
      TOXENV: "py35"
    - PYTHON: "C:/Python36"
      TOXENV: "py36"
    - PYTHON: "C:/Python37"
      TOXENV: "py37"
    - PYTHON: "C:/Python38"
      TOXENV: "py38"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  # Setup Python test tools
  - "SET STATIC_DEPS=true"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"
  - "python -m pip install -U setuptools"
  - "python -m pip install virtualenv"
  - "python -m pip install tox"
  - "python -m pip install codecov"

test_script:
  - pip --version
  - virtualenv --version
  - tox --version
  - python -m tox

after_test:
  - codecov

matrix:
  fast_finish: true
